#!/bin/bash
set -e

# Build the command as a string, not an array
if [ "$COMMON_BTC_NETWORK" == "testnet" ]; then
  SOROBAN_DOMAIN="$SOROBAN_DOMAIN_TEST"
  SOROBAN_P2P_ROOM="$SOROBAN_P2P_ROOM_TEST"
  SOROBAN_P2P_BOOTSTRAP="$SOROBAN_P2P_BOOTSTRAP_TEST"
  SOROBAN_ANNOUNCE_KEY="$SOROBAN_ANNOUNCE_KEY_TEST"
else
  SOROBAN_DOMAIN="$SOROBAN_DOMAIN_MAIN"
  SOROBAN_P2P_ROOM="$SOROBAN_P2P_ROOM_MAIN"
  SOROBAN_P2P_BOOTSTRAP="$SOROBAN_P2P_BOOTSTRAP_MAIN"
  SOROBAN_ANNOUNCE_KEY="$SOROBAN_ANNOUNCE_KEY_MAIN"
fi

# Build command arguments
CMD_ARGS="-log $SOROBAN_LOG_LEVEL"
CMD_ARGS="$CMD_ARGS -hostname $NET_DOJO_SOROBAN_IPV4"
CMD_ARGS="$CMD_ARGS -port $SOROBAN_PORT"
CMD_ARGS="$CMD_ARGS -domain $SOROBAN_DOMAIN"
CMD_ARGS="$CMD_ARGS -p2pListenPort $SOROBAN_P2P_LISTEN_PORT"
CMD_ARGS="$CMD_ARGS -p2pLowWater $SOROBAN_P2P_LOWWATER"
CMD_ARGS="$CMD_ARGS -p2pHighWater $SOROBAN_P2P_HIGHWATER"
CMD_ARGS="$CMD_ARGS -p2pPeerstoreFile $SOROBAN_P2P_PEERSTORE_FILE"
CMD_ARGS="$CMD_ARGS -p2pRoom $SOROBAN_P2P_ROOM"
CMD_ARGS="$CMD_ARGS -p2pBootstrap $SOROBAN_P2P_BOOTSTRAP"
CMD_ARGS="$CMD_ARGS -gossipD $SOROBAN_GOSSIP_D"
CMD_ARGS="$CMD_ARGS -gossipDlo $SOROBAN_GOSSIP_DLO"
CMD_ARGS="$CMD_ARGS -gossipDhi $SOROBAN_GOSSIP_DHI"
CMD_ARGS="$CMD_ARGS -gossipDout $SOROBAN_GOSSIP_DOUT"
CMD_ARGS="$CMD_ARGS -gossipDscore $SOROBAN_GOSSIP_DSCORE"
CMD_ARGS="$CMD_ARGS -gossipDlazy $SOROBAN_GOSSIP_DLAZY"
CMD_ARGS="$CMD_ARGS -gossipPrunePeers $SOROBAN_GOSSIP_PRUNE_PEERS"
CMD_ARGS="$CMD_ARGS -gossipLimit $SOROBAN_GOSSIP_LIMIT"
CMD_ARGS="$CMD_ARGS -ipcChildProcessCount $SOROBAN_IPC_CHILD_COUNT"
CMD_ARGS="$CMD_ARGS -ipcNatsPort $SOROBAN_IPC_NATS_PORT"

# Add conditional flags
if [ "$SOROBAN_ANNOUNCE" == "on" ]; then
  CMD_ARGS="$CMD_ARGS -announce $SOROBAN_ANNOUNCE_KEY"
  CMD_ARGS="$CMD_ARGS -onionFile $SOROBAN_ONION_FILE"
fi

if [ "$SOROBAN_DHT_SERVER_MODE" == "on" ]; then
  CMD_ARGS="$CMD_ARGS -p2pDHTServerMode"
fi

# Execute with proper word splitting
exec soroban-server $CMD_ARGS
